// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Footer: typeof import('D:/CODE/GITHUB/vitesse-template/src/components/Footer.vue')['default']
    Header: typeof import('D:/CODE/GITHUB/vitesse-template/src/components/Header.vue')['default']
    'Mdi:accountCircleOutline': typeof import('~icons/mdi/account-circle-outline')['default']
    'Mdi:emoticonKissOutline': typeof import('~icons/mdi/emoticon-kiss-outline')['default']
    README: typeof import('D:/CODE/GITHUB/vitesse-template/src/components/README.md')['default']
  }
}

export { }
